name = "test"

[files]
bus = "case_data/bus.csv"
branch = "case_data/branches.csv"
gen = "case_data/gen.csv"
switch = "case_data/switchgear.csv"
load = "case_data/loads.csv"
reldata = "case_data/reldata.csv"

[configuration]
baseMVA = 100.0
