name = "test2"

[files]
bus = "bus2.csv"
branch = "branches2.csv"
gen = "gen.csv"
switch = "switchgear2.csv"
loaddata = "loads.csv"
transformer = "transformers.csv"
reldata = "reldata2.csv"

[configuration]
baseMVA = 100.0
