# Configuration file for the FaSaD prototype. Test grid that Tonje Skoglund
# Hermansen has used in example calculations in Excel. The prototype should
# reproduce the results of Tonje's Excel files.

format = 'skagerak' # Format of the input data. Either 'fasad' or 'skagerak'.

name = 'CINELDI'
transmission_grid = '1' # Name of transmission grid node
reserves = ['36', '62', '88']

# Fault indicator maximum fault order. Must be a non-negative integer or 'all':
indicator_max_fault_order = 0

["configuration"]
	baseMVA = 100

[files]
	# List of files needed to run FASaD
	#transformers = ['formers.csv']
	branch = 'CINELDI_MV_reference_grid_base_branch.csv'
	reldata = 'CINELDI_MV_reference_system_reldata.csv'
	switch= 'CINELDI_MV_reference_system_switchgear.csv'
	bus = 'CINELDI_MV_reference_grid_base_bus.csv'
	load = 'CINELDI_MV_reference_system_load_point.csv'
	gen = 'gen.csv' # Not part of the data set, but added by Sigurd Jakobsen
	#fault_indicators = []

[failures]
	switch_failures = true
